from .utils import get_test_file_path
from .config import TEXT_ONLY_SMALL_PDF
from app.services import extract_info_from_pdf
import pytest

@pytest.mark.asyncio
async def test_extract_info_from_pdf():
    file_path = get_test_file_path(TEXT_ONLY_SMALL_PDF)

    with open(file_path, 'rb') as f:
        file_content = f.read()

    extracted_text, page_count = await extract_info_from_pdf(file_content)
    expected_text = '''lorem ipsum dolor sit amet, consectetur adipiscing elit. mauris ligula tellus, molestie eget est et, elementum vulputate tortor. praesent eu dapibus arcu. quisque ultricies dolor eget lacus cursus feugiat. sed egestas nulla non elit aliquam, egestas tempor urna ultricies. integer sed pellentesque nisl. fusce vel risus finibus, vehicula dolor vehicula, pharetra libero. phasellus aliquet orci eu tortor vulputate, quis aliquam felis accumsan. class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. sed porta ornare semper. curabitur dolor massa, consequat ac luctus a, facilisis vitae est. donec porta vulputate molestie. donec quis lacinia ante, quis sollicitudin erat. maecenas leo tellus, faucibus a sem a, pretium lacinia risus. suspendisse facilisis commodo tincidunt. suspendisse sit amet neque sit amet ipsum sagittis cursus at id est. nunc aliquet et risus quis pellentesque.
suspendisse ultricies purus tortor, sed euismod leo finibus at. aliquam at dapibus sapien, id rhoncus ante. vestibulum placerat, turpis vel efficitur luctus, odio magna sollicitudin quam, in egestas quam sapien et sapien. nullam aliquam hendrerit risus. in ex lectus, convallis id purus et, sollicitudin ultricies lectus. phasellus sit amet lectus in nibh finibus cursus. pellentesque porttitor mauris in metus tempor, quis ultricies nunc porta. nulla facilisi. class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. donec euismod rhoncus turpis, sit amet luctus augue accumsan sollicitudin. fusce augue nibh, pulvinar eu convallis eu, condimentum non neque. curabitur eu ex risus. integer mollis at dui vel consectetur. donec et eros tincidunt, semper elit ut, lobortis velit. vivamus suscipit ullamcorper nibh, in ullamcorper lorem malesuada eu.
sed porta commodo arcu in gravida. proin dictum est accumsan, aliquam sapien fermentum, venenatis mauris. donec faucibus libero id augue molestie convallis. praesent fringilla luctus ante, quis interdum metus maximus in. morbi a neque non sapien tincidunt venenatis ac eget ante. nullam turpis enim, ultricies in imperdiet porttitor, blandit iaculis neque. aliquam erat volutpat. mauris at eros elementum, tempus ante non, viverra turpis. vestibulum consequat risus ac metus suscipit, sed iaculis ante fermentum. maecenas sagittis molestie ligula, vel interdum justo imperdiet sed.
etiam rutrum elit sit amet ipsum iaculis porta. curabitur tristique, dolor a euismod hendrerit, neque magna scelerisque dolor, vel vehicula sem turpis iaculis nunc. nullam in molestie ipsum. nullam ullamcorper sed risus vitae tempus. mauris facilisis erat pharetra est malesuada commodo. pellentesque porttitor leo nec velit blandit dignissim. quisque eu est et nulla fermentum vestibulum. nunc semper risus nec odio accumsan fermentum. donec eget augue ultrices, scelerisque sem non, viverra ex. praesent efficitur porta feugiat. suspendisse ligula massa, lacinia congue faucibus non, sollicitudin sed dui. etiam aliquam non nunc et tempus. pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. suspendisse vitae tincidunt dolor.
aliquam eget mi ac augue porta laoreet sit amet ac nulla. vivamus laoreet nisi ac enim tempor elementum. proin at mi ultricies, sagittis diam quis, dapibus libero. cras nunc purus, porta ac sollicitudin id, dignissim ut purus. nullam in lacus eu lacus finibus laoreet. nunc eget sem at massa pellentesque ornare vitae ut nunc. nulla commodo, nunc eu mollis mattis, ipsum justo efficitur neque, vitae posuere arcu neque eget felis. donec nec sem sed turpis viverra ullamcorper a eget dui. nullam tellus enim, cursus a dictum in, convallis at ipsum. cras hendrerit nunc leo, in dignissim justo accumsan at. phasellus ac pellentesque sem. praesent a ligula eu orci aliquet rhoncus. integer id nulla felis. praesent vitae euismod nisi, sit amet tristique justo. cras congue mauris ut est gravida venenatis.
phasellus fermentum tincidunt bibendum. sed rhoncus ultrices urna, in faucibus justo condimentum et. aliquam sit amet urna nec turpis hendrerit pharetra nec ut tortor. vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; suspendisse hendrerit, nisi eu blandit efficitur, eros enim porta libero, nec euismod leo orci at tellus. donec ut diam sagittis augue lacinia consequat ultrices nec sem. ut aliquam magna magna, nec interdum dui sollicitudin in. maecenas laoreet faucibus felis, in rhoncus felis congue ut. phasellus ultricies neque vitae ipsum vulputate porta. mauris in lectus purus. sed rutrum fermentum ante, eu posuere ante commodo tempor. vivamus sollicitudin, purus id iaculis aliquam, nunc lectus interdum magna, nec sollicitudin erat sem at ipsum. pellentesque finibus pharetra ante et tristique.
curabitur malesuada, ligula eget interdum interdum, ex nibh auctor enim, eu ullamcorper est turpis sit amet ante. morbi feugiat convallis augue, id faucibus ante convallis ullamcorper. suspendisse potenti. vestibulum egestas quam vel enim sollicitudin volutpat id sit amet arcu. ut dui elit, interdum quis placerat sed, imperdiet a erat. quisque dictum quis dolor vel dignissim. in sed dui eleifend, tincidunt lorem eget, sodales diam. donec vitae magna pellentesque, maximus orci at, viverra ex. donec luctus mauris nec gravida luctus. integer a enim eu tellus aliquam aliquam sed et turpis. phasellus a volutpat mi, ac tempor diam. phasellus nec nunc sollicitudin ex accumsan bibendum. nullam condimentum velit gravida suscipit porttitor.
duis interdum tristique leo vitae congue. sed porttitor vulputate massa ac lobortis. pellentesque volutpat vestibulum velit, ut aliquam nisi feugiat nec. mauris sodales, nunc at fermentum consectetur, libero nulla facilisis nibh, vel mollis diam massa id lacus. donec mollis, nulla vel condimentum condimentum, risus metus luctus massa, fringilla placerat est odio ac erat. duis justo turpis, aliquam at tellus pretium, mattis gravida velit. vivamus congue placerat sem, sit amet volutpat metus imperdiet vel. curabitur non vestibulum massa. nam tempor dapibus varius.
maecenas id massa ac ligula blandit malesuada sit amet quis nisi. quisque vitae molestie ipsum, ut aliquam purus. duis vulputate ex molestie velit dapibus malesuada. aliquam aliquam ac sapien sit amet euismod. aliquam convallis mattis sem scelerisque pellentesque. ut pretium ante purus, a hendrerit ante viverra vel. aliquam quis lobortis mauris, nec blandit enim. fusce id nulla condimentum, efficitur elit eget, elementum odio.
integer eget ante quis lectus tempor porttitor. integer ut sem non mi dictum viverra et nec arcu. proin suscipit commodo nisl. etiam tempus, eros in elementum sodales, sem dolor aliquam orci, nec congue mauris lorem ut nunc. quisque auctor nisi id ex lobortis molestie. nam sed mi id quam ornare dictum ac id lacus. phasellus ut nisi ac lectus aliquet condimentum. in lobortis libero vel dictum lacinia. integer lobortis turpis at pretium tempor. aliquam non leo aliquam, ultricies est vel, dapibus turpis. pellentesque posuere mi felis, eget scelerisque mi ultrices sit amet. etiam urna massa, venenatis a iaculis at, ullamcorper laoreet nulla. sed id elit mattis, hendrerit ipsum ac, accumsan augue. praesent interdum ultrices nisl ut bibendum. vivamus vehicula est massa, ultrices porta turpis rhoncus ut. curabitur congue mi augue, et laoreet lectus convallis eu.
aenean ac metus eu dolor aliquet commodo ut laoreet dolor. fusce ac mauris a nibh tristique ultrices ut eu neque. interdum et malesuada fames ac ante ipsum primis in faucibus. suspendisse ultrices ex vel elit euismod, fermentum rutrum lacus hendrerit. integer id dui mollis, bibendum tellus non, pellentesque lectus. vivamus et neque vulputate, laoreet urna in, porta diam. donec ullamcorper tellus eu purus tincidunt euismod. mauris non elit nec massa consequat cursus eget at tellus. donec non nisi nunc. orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. praesent consectetur eget dolor vitae eleifend. donec auctor mauris velit, ac luctus nunc dignissim et. nullam rhoncus risus id nulla suscipit bibendum. etiam at diam et nisi venenatis faucibus. aenean finibus erat tellus, id consectetur nisl consequat nec. mauris sapien massa, rutrum volutpat purus quis, mollis iaculis nisi.
vestibulum congue porttitor consequat. maecenas eget dolor placerat, tristique dui ut, iaculis velit. nullam ac justo gravida, hendrerit justo eget, feugiat urna. suspendisse quis ipsum sodales, lobortis nisl vel, hendrerit nibh. nulla tincidunt lorem ut libero viverra malesuada. vestibulum sollicitudin odio ut lacinia ullamcorper. etiam nunc felis, ornare quis elit ac, facilisis vehicula purus. phasellus vel sapien nulla. aliquam eu eros lorem. fusce finibus, purus ac mollis commodo, urna nisi maximus arcu, id interdum risus sem vel odio. pellentesque eu eleifend orci. etiam vitae tristique lacus, a volutpat mi. nunc quis finibus ante, sed malesuada nunc. nulla id cursus risus, vitae ullamcorper dui. nam vehicula nunc ac velit dapibus convallis.
suspendisse est nunc, scelerisque id ullamcorper eu, tincidunt sed quam. aliquam egestas et velit eget pretium. maecenas eleifend mattis aliquam. nam feugiat varius bibendum. proin a vulputate mauris. morbi id augue tincidunt, malesuada nisl vitae, lacinia sem. etiam ut est nibh. sed facilisis, arcu in porta tristique, ex arcu pulvinar enim, nec condimentum urna lectus ac lectus.
cras convallis neque imperdiet magna porta, eget rutrum nunc dapibus. vivamus aliquam nulla lorem, id congue ex malesuada sed. sed dapibus nec leo sit amet cursus. nam et erat ante. suspendisse id orci at lectus pharetra gravida sed et elit. donec vitae est a enim sollicitudin rutrum id id orci. proin malesuada felis vel eros condimentum laoreet.
sed pulvinar orci eu tristique dapibus. cras cursus tellus purus, eu vulputate justo aliquet ut. cras eleifend dui sit amet purus tempus, vel feugiat massa pharetra. donec sagittis euismod ultricies. praesent non lorem justo. suspendisse et tempus neque, quis dictum orci. praesent vel elit orci. donec eu consectetur ligula, ultricies gravida ipsum. suspendisse potenti.
sed eget lacus lacus. fusce tempor enim quis elit maximus, vitae rutrum felis pretium. cras imperdiet et quam vitae iaculis. donec finibus, ante sit amet imperdiet dignissim, justo justo posuere mi, fringilla suscipit orci lorem quis eros. sed at tincidunt ex. cras pellentesque lectus vel fringilla volutpat. integer leo risus, placerat id velit ac, ornare lobortis leo. class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. cras eu sem ac nulla tempus rutrum quis a arcu.
cras et nulla eu massa blandit sagittis sit amet ac sem. aliquam rhoncus finibus efficitur. praesent non tristique est. curabitur et iaculis sapien. mauris vehicula sit amet dui in pulvinar. vivamus vehicula ante ut neque vestibulum gravida. duis a tempor orci, non sollicitudin est. duis feugiat, orci sed ultricies vestibulum, nunc ex lacinia magna, eget facilisis ipsum magna ut ante. morbi id nulla eu magna ullamcorper interdum ut ut quam. suspendisse at faucibus velit. cras lacinia augue vitae semper dapibus. donec sed augue tempus, suscipit enim eget, laoreet lectus. aliquam faucibus mollis purus et porta.
orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. nunc et risus neque. morbi congue purus vel mi mattis, a lobortis justo lacinia. vivamus quis lobortis quam, ac congue augue. nullam hendrerit tincidunt risus, convallis rutrum orci suscipit id. vestibulum accumsan vestibulum erat non condimentum. vestibulum laoreet tortor ut scelerisque molestie. donec gravida sollicitudin fermentum. curabitur ultricies, felis nec vehicula cursus, justo eros fermentum purus, eu suscipit turpis sem at urna. sed faucibus lectus quis tortor dictum blandit. vestibulum auctor nisi eget pellentesque elementum. aliquam ultricies congue nibh, in efficitur arcu cursus id. duis euismod ante at velit commodo dignissim. quisque malesuada tincidunt diam, a malesuada turpis luctus at. ut volutpat ipsum metus, quis laoreet diam dignissim at.
curabitur a tellus non purus pharetra luctus posuere et risus. pellentesque vel ex et nibh sagittis scelerisque. class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. phasellus vulputate lorem non nisi posuere, ut pharetra augue rhoncus. vestibulum elementum nunc libero, eu malesuada justo feugiat in. fusce malesuada imperdiet nisi, eu placerat diam. aliquam vel feugiat dolor. duis est velit, pretium eget rhoncus a, hendrerit eu nisl. pellentesque sagittis mauris ut placerat pretium. donec accumsan cursus diam ultrices viverra. quisque quis lorem purus. curabitur at metus non purus interdum imperdiet.
donec venenatis faucibus libero ac faucibus. pellentesque sollicitudin, mauris a fringilla tincidunt, est augue suscipit mauris, quis pulvinar risus metus eget turpis. pellentesque egestas risus id fermentum cursus. sed turpis odio, venenatis quis sapien eu, efficitur malesuada enim. lorem ipsum dolor sit amet, consectetur adipiscing elit. vivamus ac leo et nibh molestie lobortis sit amet sed odio. praesent tincidunt nec erat sed dignissim. nullam vitae ullamcorper justo. sed cursus arcu eget turpis sodales luctus. morbi a sapien et mi mollis auctor. etiam congue, lectus non malesuada maximus, ante libero pellentesque sem, quis convallis nunc mauris sed nisi. sed lacinia diam in eros dapibus tempor. sed faucibus ornare metus ac elementum.
pellentesque pretium imperdiet diam, id posuere urna iaculis in. donec eu tempus turpis. vivamus et nisi finibus, sagittis nisl et, tristique felis. in interdum massa ac dignissim eleifend. proin convallis, dolor id euismod tristique, nisi augue accumsan mauris, vitae ullamcorper nulla odio et sem. in ac sem et arcu tincidunt tempus. suspendisse euismod lacus ut posuere bibendum. duis tincidunt dapibus pharetra. morbi vel tortor id turpis sollicitudin mollis id a est. in condimentum rutrum facilisis. duis et semper purus, faucibus egestas ipsum. donec blandit nisl sit amet varius tristique.
suspendisse blandit velit et risus lacinia, varius placerat velit euismod. in justo dolor, viverra non interdum sit amet, molestie ut urna. suspendisse feugiat augue ac mattis feugiat. nullam luctus at sem a vehicula. sed lorem neque, gravida et ultricies ac, interdum auctor nibh. aenean non nisl sit amet tortor auctor aliquam. pellentesque faucibus tellus ut neque consequat luctus.
mauris ultrices mauris non velit fermentum luctus. mauris ac odio ut sem sagittis vehicula nec ac dolor. nunc tempus magna velit, vel dapibus purus varius a. donec scelerisque arcu sed lacus aliquet scelerisque. fusce eu lacinia neque. nunc nulla nunc, dignissim ac nibh eget, maximus maximus justo. curabitur eget sagittis diam, nec porttitor dolor. duis interdum ante in sem tempor, non tincidunt orci tincidunt. mauris et dolor sodales, eleifend lectus in, viverra orci. etiam felis turpis, efficitur id feugiat id, luctus vitae dui. integer at arcu nec ex ullamcorper rhoncus. pellentesque ullamcorper augue in lacus pulvinar, id posuere dolor pharetra. donec in accumsan augue, ut facilisis lectus. sed nec ligula ac arcu vulputate semper. donec a tellus ipsum. nullam nisi leo, maximus a luctus sed, eleifend ut mi.
duis sit amet porttitor sapien. aliquam tempor, tortor eget vehicula porttitor, odio turpis auctor est, ut pharetra lacus magna nec turpis. mauris a ex felis. nunc vitae suscipit nulla, at aliquet purus. pellentesque sed massa ut dui rutrum porta. curabitur ante ex, maximus sed imperdiet eget, pulvinar vel arcu. donec iaculis id ligula in condimentum. cras eget velit at metus maximus lobortis et id urna. fusce sagittis turpis eu dapibus pharetra. aliquam sem ligula, lobortis eget dignissim ac, mollis nec purus. vestibulum at lectus pharetra diam volutpat congue sit amet eu lectus.
cras dui felis, faucibus ut sem quis, malesuada vestibulum dolor. maecenas feugiat fermentum risus a luctus. pellentesque elit ligula, varius imperdiet hendrerit a, tempus id neque. interdum et malesuada fames ac ante ipsum primis in faucibus. proin vitae ex justo. quisque convallis dolor non sagittis efficitur. etiam consequat, diam at aliquam malesuada, arcu orci molestie diam, malesuada congue ante enim eget eros. vivamus justo metus, rhoncus vel pretium in, rutrum vitae leo. etiam sagittis, odio in luctus finibus, sapien nulla rutrum ligula, ut convallis lectus metus non urna. ut hendrerit neque sed malesuada tempor. vivamus quis dolor ante. cras et tempus odio. ut rutrum felis vitae nisl rutrum viverra.
duis placerat dui ac est tempor, faucibus lobortis enim porttitor. pellentesque eget erat lacinia, aliquam urna aliquam, eleifend leo. aliquam semper sit amet orci ac aliquet. nam suscipit efficitur pellentesque. mauris dignissim venenatis nibh, vitae suscipit leo dignissim nec. vestibulum aliquet at lectus ut tempor. integer porta velit pulvinar ipsum volutpat dictum. lorem ipsum dolor sit amet, consectetur adipiscing elit. nulla scelerisque vitae odio sit amet fermentum. curabitur vehicula massa commodo, faucibus ante vel, pretium elit. sed vitae dui magna.
aliquam eget eros volutpat, ullamcorper elit eu, feugiat diam. mauris cursus nisi et venenatis euismod. praesent eu tellus vitae mi sagittis congue id vitae urna. praesent fermentum nunc et lorem tempor, at rutrum erat convallis. mauris ac orci at justo varius mattis vel sed ex. nulla felis nunc, sodales porta urna eu, tristique pellentesque felis. suspendisse ut mi vel turpis elementum molestie. nullam sagittis nisi nunc, quis vestibulum urna fringilla tincidunt. quisque quis leo faucibus, pulvinar ex ac, volutpat ante. duis commodo ultrices velit, vel vulputate mauris posuere ac.
in hac habitasse platea dictumst. etiam quis eros in metus blandit tincidunt. in semper non ipsum fringilla ullamcorper. phasellus cursus vel dolor non lobortis. in non nisi odio. curabitur egestas massa tellus, sit amet imperdiet arcu euismod id. fusce fermentum leo magna. donec vitae elementum sem. morbi sit amet leo accumsan, aliquam felis id, facilisis urna.
praesent fringilla massa et tortor suscipit, sed sagittis libero egestas. aliquam erat volutpat. nullam porttitor pellentesque venenatis. in eu ullamcorper quam, non maximus arcu. quisque pulvinar blandit turpis eget dapibus. aliquam non lacus pharetra ex viverra congue. mauris commodo velit sed nisl facilisis imperdiet. phasellus cursus elit nunc, non efficitur dui interdum in. in sed ultricies nulla. aenean at lorem lacinia ante finibus sagittis. aliquam vel neque id ipsum viverra maximus vitae sit amet lorem. ut mattis nisi vitae neque consequat tincidunt.
vestibulum at turpis eu arcu eleifend porta. curabitur sem odio, interdum nec iaculis vel, tincidunt ac eros. fusce mauris quam, lobortis sit amet urna ut, rhoncus ullamcorper nisl. fusce et euismod erat, a accumsan enim. duis maximus ipsum ultrices metus tempor lobortis. donec varius purus dui. in vitae dignissim elit, nec gravida metus. etiam lacus nisi, ultrices nec metus sed, tempor fringilla velit. nam at est et nisl sollicitudin mattis nec vel nisl. cras iaculis diam eu fermentum fringilla. vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; vestibulum commodo urna nisl, id imperdiet urna facilisis nec. morbi dui elit, aliquam vitae quam id, tempus egestas velit. cras elementum feugiat sagittis.
aenean eu sollicitudin magna, a condimentum est. nullam fringilla odio erat, tempus rutrum neque consequat eget. nunc porttitor elit quis cursus fermentum. vivamus ultricies massa eget euismod sodales. aenean a nulla laoreet, commodo libero sit amet, semper augue. praesent pretium purus vel lectus egestas sagittis. nullam vel hendrerit lorem. mauris sit amet leo accumsan, auctor urna volutpat, vehicula mi. ut interdum neque vel nibh egestas scelerisque. quisque dapibus fermentum felis at pulvinar. etiam quis pellentesque enim. vestibulum gravida, mauris sit amet gravida dignissim, lorem sem vehicula nisl, id consequat felis sapien ut massa. mauris ac volutpat quam, ac pellentesque libero. quisque et ante vel sapien pellentesque ultricies.
cras et congue risus. praesent sit amet elit sed purus aliquet volutpat. ut sed mattis justo. duis sed tortor eget leo euismod aliquet ut eget quam. vestibulum finibus, orci et viverra semper, sem nulla tincidunt velit, ut laoreet mi tellus vel odio. cras velit lacus, suscipit id mi vitae, volutpat pulvinar mi. sed venenatis commodo scelerisque. fusce ac posuere diam. proin tortor sapien, vulputate vitae dui quis, sodales rutrum tortor. donec ut nunc pellentesque, ultrices lacus ac, ultricies eros. praesent pulvinar porta eros sit amet pellentesque.
nam vulputate pulvinar tortor, sollicitudin ornare velit mattis sit amet. vivamus maximus lobortis ornare. etiam ac bibendum metus, at semper mauris. curabitur ac mi sit amet erat maximus gravida in vel velit. mauris quam nulla, tincidunt quis faucibus et, ultricies et dui. morbi vulputate pulvinar accumsan. sed nec nisl a dui venenatis faucibus. nullam quis lobortis neque. vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; vestibulum elit tellus, aliquam eget volutpat at, accumsan non arcu. in lobortis orci id finibus fringilla.
nam id tempor leo. nam pharetra urna quis lorem venenatis scelerisque. maecenas fringilla sem in odio sodales bibendum. morbi in tempus nunc. cras eu pellentesque ante. nulla vitae convallis nisi. sed maximus placerat magna nec aliquet. ut ultricies elit purus, ut feugiat magna aliquet non.
vivamus feugiat tincidunt nunc, non sagittis mauris mollis id. ut odio nisi, blandit ac tellus ac, porttitor feugiat risus. donec eros orci, porttitor id diam quis, mollis dapibus odio. nullam sollicitudin, risus vulputate scelerisque tincidunt, libero leo placerat ante, eu sollicitudin dolor velit at erat. integer elementum mi risus, id dictum turpis accumsan id. cras sit amet sapien nisi. sed eros sapien, rutrum at est bibendum, porttitor rutrum dui. aenean mollis ligula non massa mattis malesuada.
phasellus porttitor neque eros, a varius lorem faucibus nec. pellentesque leo libero, congue a felis nec, auctor fermentum massa. nunc varius nec nunc non condimentum. mauris ultricies cursus consectetur. nullam sodales metus leo, a auctor odio sagittis non. ut nec enim egestas, convallis nisi id, rhoncus elit. integer pellentesque lacus a odio lobortis, vel ullamcorper nisi hendrerit. vestibulum non eros venenatis, aliquet leo in, suscipit urna. donec sagittis in odio ac pulvinar. donec quis erat accumsan, venenatis nibh non, aliquet risus. suspendisse eleifend semper tincidunt. fusce cursus consectetur consequat. phasellus vehicula nisi tellus, sit amet euismod est molestie sit amet. phasellus venenatis augue lacus. integer porta ultricies pretium.
morbi tempus molestie posuere. duis scelerisque sapien varius, rhoncus mauris sit amet, ornare sem. aenean vel vulputate dolor. vestibulum at dictum turpis, sed sagittis nisl. proin imperdiet dignissim dui, eu cursus mi finibus in. nam porta purus eget odio ultrices vulputate. curabitur et auctor leo, a porta enim. nulla nunc elit, vestibulum eu neque vel, congue sagittis eros. vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
cras tempor ipsum nec justo fringilla, sodales aliquet quam posuere. mauris at molestie quam. mauris quis justo non diam pulvinar pulvinar. curabitur varius orci dui, eget venenatis lorem fringilla vitae. orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. etiam blandit, ante dignissim mattis fringilla, nisi ante interdum nunc, in dictum enim sem fermentum mi. fusce porta vel orci in congue. proin nec tellus risus. aenean blandit orci sit amet hendrerit tincidunt. aliquam non dui et justo tincidunt tincidunt a eget nunc.
nunc bibendum eros ac massa blandit condimentum. donec a sem dignissim, tempus magna vitae, maximus eros. duis pretium nulla nec cursus feugiat. quisque vel tincidunt nibh. maecenas consequat pellentesque feugiat. fusce at ligula ac ante porta finibus. integer sed molestie lectus, vitae hendrerit ligula. in ut nulla ornare, pulvinar augue interdum, dapibus lorem. vivamus vel quam eleifend, lacinia tellus ut, mattis libero. quisque vestibulum enim ac dui tincidunt consequat. mauris ornare, lorem quis pulvinar bibendum, turpis metus bibendum enim, in bibendum arcu lectus a mauris. ut porta enim at facilisis hendrerit. ut dignissim, metus vel sollicitudin fringilla, nisl magna eleifend sapien, quis viverra quam leo eget leo. donec ultrices aliquam est, ut faucibus quam euismod ac. aenean fringilla augue eu mauris sodales blandit. quisque molestie nec mi non interdum.
cras laoreet erat sed odio ultricies fermentum. vestibulum at tempor ipsum. quisque aliquam ipsum arcu, nec sodales libero placerat sit amet. curabitur sit amet augue sit amet turpis rhoncus volutpat ut vel lectus. sed vitae augue ac dui tincidunt faucibus eget et augue. donec in felis a nisl viverra elementum id id justo. fusce sollicitudin, justo ultricies tempor dignissim, lorem tellus rhoncus magna, laoreet rutrum dolor turpis ut ipsum. suspendisse et facilisis arcu, ac rutrum odio. etiam nec sapien pretium mauris consectetur volutpat eget nec nulla. aliquam feugiat tincidunt auctor. nunc vel fringilla arcu. quisque magna purus, pellentesque id ultricies fringilla, pretium quis diam. proin faucibus bibendum commodo. cras eu nulla suscipit leo sollicitudin pulvinar. pellentesque felis nibh, porta non volutpat at, lacinia non sapien.
quisque nisi elit, scelerisque et eros nec, feugiat semper nibh. proin id tellus sed erat auctor fermentum. praesent elementum ante sit amet lacus varius tempor. praesent sit amet libero arcu. proin ut felis non quam ornare auctor sed in ligula. vivamus posuere sem eu ante vestibulum, id posuere est viverra. duis lacinia urna et diam posuere porta. in vel malesuada risus. in ac euismod nisl. lorem ipsum dolor sit amet, consectetur adipiscing elit. praesent lacus ante, luctus ac urna at, ornare cursus erat. fusce ultrices, nisl sed tincidunt tincidunt, massa mi elementum felis, et luctus lorem sapien ut ante. morbi id pellentesque nibh, vitae vestibulum massa. etiam fermentum dignissim mauris, at vestibulum quam. morbi vehicula massa eget congue facilisis.
suspendisse quis elit vestibulum, gravida tellus in, rutrum nunc. aenean non eleifend felis. curabitur aliquet mi lacinia, egestas est condimentum, ornare urna. integer dictum rutrum ornare. sed eu bibendum augue. mauris dapibus semper fermentum. vestibulum et porttitor velit. mauris lobortis efficitur nisl, a consectetur nisl interdum vel. sed sed nunc vitae purus convallis eleifend. suspendisse sodales pretium nisl, sed lacinia justo convallis eu. nam eu ultrices magna. sed tempor lectus ac justo rhoncus aliquam. vestibulum dictum ante vitae eros tempus, ut pulvinar urna sodales.
praesent imperdiet neque ut dui bibendum blandit. praesent varius ac ex in dapibus. orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. fusce viverra augue sit amet turpis lacinia tincidunt. sed aliquam felis nec erat blandit hendrerit. curabitur sed vestibulum tellus. maecenas fermentum consequat lacus, vitae venenatis ex varius at. fusce rhoncus egestas sapien, vitae semper odio imperdiet elementum. nam pretium condimentum mauris, at eleifend sapien vehicula vitae. duis fringilla nisi ac metus ornare, quis tempus tellus elementum. integer sit amet odio dui. sed et ultricies velit, a sodales urna. nullam et elit mattis, pretium elit iaculis, euismod orci. sed ex neque, tincidunt non sodales eget, fringilla nec metus.
etiam nisl ex, convallis a felis ultricies, pharetra pellentesque nisl. ut ac porta velit. proin vulputate eu tellus sit amet varius. curabitur id interdum lacus. etiam dictum consectetur lectus non viverra. curabitur laoreet sagittis tortor et accumsan. integer a ex eleifend erat mattis condimentum. integer pellentesque urna et nibh aliquam aliquet. aenean justo risus, ultrices eget pellentesque ut, vestibulum sodales dolor. lorem ipsum dolor sit amet, consectetur adipiscing elit. cras quis dui in sapien placerat sodales.
in pharetra neque leo, a eleifend enim elementum in. sed quis dui ac ex placerat tempus. morbi aliquam sollicitudin ligula, ac malesuada est commodo vel. vivamus viverra dui nec lobortis gravida. vivamus mauris nulla, convallis eu vestibulum vel, dictum vitae velit. sed venenatis tristique purus. donec at justo iaculis, venenatis mauris ut, faucibus enim. sed ut ullamcorper ipsum. fusce et neque ac massa vulputate fermentum. ut maximus vel nibh vel suscipit. aenean at nisi porttitor, rhoncus elit porttitor, malesuada nibh. in vitae dui quis ipsum dictum elementum sit amet molestie diam. suspendisse sollicitudin turpis ante, eu suscipit augue gravida non. aliquam nec diam nec nibh luctus tempor. donec porttitor aliquet est, blandit ultricies odio pulvinar nec.
sed nisi tellus, convallis id ipsum nec, pharetra sollicitudin enim. in ac neque in felis aliquam aliquet. aliquam justo nulla, pharetra sed egestas interdum, accumsan vitae enim. pellentesque finibus sagittis aliquam. mauris non blandit leo. mauris elementum interdum quam quis viverra. fusce eu risus vel augue sodales placerat. vestibulum nulla purus, tincidunt vitae sem at, placerat pretium mi. praesent eu est ac felis fringilla rutrum. mauris quis pharetra lacus. donec mi odio, finibus eu luctus pharetra, molestie eget sem. quisque egestas interdum suscipit.
cras cursus nec nisl quis tincidunt. sed sed mattis lacus, at vestibulum urna. praesent condimentum molestie odio, tristique accumsan arcu dictum nec. phasellus et sem diam. etiam posuere porttitor urna, sit amet sollicitudin sem malesuada sit amet. suspendisse potenti. integer sit amet imperdiet lorem. cras diam quam, ornare auctor rutrum quis, vestibulum sed ipsum.
nullam sapien nunc, euismod nec viverra eu, ullamcorper in urna. quisque posuere at nibh ac condimentum. vestibulum id sapien at orci fringilla mollis. curabitur aliquam posuere tristique. sed risus dui, consectetur viverra commodo ac, fringilla eu velit. pellentesque nec consectetur odio, et semper arcu. maecenas pharetra quam sed leo auctor, at sodales turpis pellentesque. suspendisse non tincidunt lorem, ut commodo mauris. curabitur viverra neque lectus, tempus lobortis dolor feugiat sed. phasellus ac ligula eget felis feugiat consequat eu non lorem. proin posuere, quam eget vestibulum iaculis, erat lorem interdum tortor, in ultrices ligula velit a arcu. donec eget dapibus lectus, at ultricies quam. praesent vehicula hendrerit quam, sit amet mollis enim pharetra eget. proin vitae nulla sagittis, mattis libero sit amet, convallis nulla.
fusce vitae rhoncus metus. duis efficitur nisi id finibus volutpat. vestibulum leo orci, congue id vehicula porta, pellentesque non sem. praesent egestas, dui vel mollis aliquam, urna ante sodales ipsum, nec congue velit urna commodo purus. suspendisse quis elit sed augue tempus interdum eu eget nunc. praesent ac odio sagittis, laoreet tortor sed, eleifend felis. vestibulum eget urna vel tortor fringilla auctor. vestibulum libero tortor, laoreet in leo et, iaculis ultrices diam.
donec pellentesque ligula quis orci scelerisque, quis tempus velit molestie. sed molestie enim ante, et semper est lobortis ac. praesent pretium nulla eget ex lobortis cursus. nullam dictum libero vel sem accumsan consequat. suspendisse in libero feugiat purus molestie accumsan. nulla nulla erat, molestie ut maximus quis, sodales ut nibh. maecenas sed sem enim. maecenas vestibulum eros turpis, sit amet ultricies dolor porta posuere. phasellus fringilla, est at malesuada aliquam, mauris augue suscipit elit, non ultrices massa nisl id eros. aenean sodales erat a quam porttitor, id venenatis risus gravida. nam ultrices neque ut aliquam eleifend.
'''
    assert ''.join(extracted_text.split()) == ''.join(expected_text.split())
    assert page_count == 8
